#this program receives personal information from users
print('personal information')
name=input('your name is')
country=input('your country is')
state=input('what state are you from')
address_of_residence=input('where do you live')
age=input('what is your age')
marital_status=input('what is your marital status')
sex=input('what is you sex')
work=input('what is your occupation')
print('my name is'+ name)
print('my country is'+ country)
print('i am from'+ state)
print('i am from'+ address_of_residence)
print('i am'+ age)
print('i am '+ marital_status)
print(sex)
print('i am a/an'+ work)

