#python program to solve matrix determinant
a=int(input('what is a'))
b=int(input('what is b'))
c=int(input('what is c'))
d=int(input('what is d'))
e=int(input('what is e'))
f=int(input('what is f'))
g=int(input('what is g'))
h=int(input('what is h'))
i=int(input('what is i'))
j=((a)*(e*i-h*f))
k=((-b)*(d*i-g*f))
l=((c)*(d*h-g*e))
print(j*k*l)
